### ISSUE TITLE
Sharing iP code quality feedback [for @malwaregarry]

### ISSUE THREAD

**Issue by soc-se-script** [malwaregarry/ip#3]
@malwaregarry We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/duke/task/Task.java` lines `10-10`](https://github.com/malwaregarry/ip/blob/c0531ba0ba0c300dbce4dd8b64c0d387a7b801cd/src/main/java/duke/task/Task.java#L10..L10):

```java

    protected static final boolean INCOMPLETE = false;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/TaskList.java` lines `42-47`](https://github.com/malwaregarry/ip/blob/c0531ba0ba0c300dbce4dd8b64c0d387a7b801cd/src/main/java/duke/TaskList.java#L42..L47):

```java

    /**
     * Add task to list.
     *
     * @param task Task to add.
     * @return Task which was added.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by malwaregarry** [comment]
fixed in 36147dfceb2befbb5f2ea7353d71686f0f039d8b
